-- 3D avatar models generated by an image-to-3D API (fal.ai Trellis, Tripo or Meshy) from an avatar
-- photo or a realistic try-on image. The GLB is stored privately in the user's folder.

create table public.avatar_models (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  source_kind text not null check (source_kind in ('avatar', 'tryon')),
  source_id uuid not null,
  status text not null default 'pending' check (status in ('pending', 'ready', 'failed')),
  engine text,                     -- model key from the AI config that produced it
  provider_ref jsonb,              -- the provider's task id while generating, so a slow job can resume
  model_path text,                 -- <user>/models/<id>.glb
  bytes int,
  error text,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);
create index avatar_models_user on public.avatar_models (user_id, created_at desc);

alter table public.avatar_models enable row level security;
-- Users read, request and delete their own models; only the job handler writes status and files.
create policy "read own" on public.avatar_models for select to authenticated using (user_id = (select auth.uid()));
create policy "create own" on public.avatar_models for insert to authenticated
  with check (user_id = (select auth.uid()) and status = 'pending' and model_path is null and provider_ref is null);
create policy "delete own" on public.avatar_models for delete to authenticated using (user_id = (select auth.uid()));

-- These APIs cost money per model, so they get their own small daily cap.
alter table public.usage_counters add column model3d_calls int not null default 0;

create or replace function public.take_usage(p_kind text, p_cap int) returns int
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_day date := (now() at time zone 'Asia/Kolkata')::date;
  v_count int;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if p_kind not in ('stylist_calls', 'tag_calls', 'tryon_calls', 'upload_urls', 'model3d_calls') then raise exception 'bad kind'; end if;

  insert into public.usage_counters (user_id, day) values (v_uid, v_day)
  on conflict (user_id, day) do nothing;

  execute format(
    'update public.usage_counters set %1$I = %1$I + 1 where user_id = $1 and day = $2 and %1$I < $3 returning %1$I',
    p_kind)
  into v_count using v_uid, v_day, p_cap;

  return coalesce(v_count, -1);
end;
$$;

-- The bucket held only images; GLB models are larger binary files.
update storage.buckets
set allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'model/gltf-binary'],
    file_size_limit = 52428800 -- 50 MB
where id = 'wardrobe';

-- Queue and service-role wrappers, as for try-on jobs.
select pgmq.create('model3d_jobs');

create or replace function public.enqueue_model3d_job() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform pgmq.send('model3d_jobs', jsonb_build_object('model_id', new.id, 'user_id', new.user_id));
  return new;
end;
$$;
create trigger avatar_models_enqueue after insert on public.avatar_models
  for each row execute function public.enqueue_model3d_job();

create or replace function public.read_model3d_jobs(p_qty int, p_vt int)
returns table (msg_id bigint, read_ct int, message jsonb)
language sql security definer set search_path = '' as $$
  select m.msg_id, m.read_ct, m.message from pgmq.read('model3d_jobs', p_vt, p_qty) m;
$$;
create or replace function public.finish_model3d_job(p_msg_id bigint) returns void
language sql security definer set search_path = '' as $$
  select pgmq.delete('model3d_jobs', p_msg_id);
$$;
create or replace function public.give_up_model3d_job(p_msg_id bigint) returns void
language sql security definer set search_path = '' as $$
  select pgmq.archive('model3d_jobs', p_msg_id);
$$;

do $$
declare f text;
begin
  foreach f in array array['read_model3d_jobs(int, int)', 'finish_model3d_job(bigint)', 'give_up_model3d_job(bigint)'] loop
    execute format('revoke all on function public.%s from public, anon, authenticated', f);
    execute format('grant execute on function public.%s to service_role', f);
  end loop;
end $$;

-- The scheduler also wakes the runner for waiting 3D model jobs.
create or replace function private.trigger_job_runner() returns void
language plpgsql security definer set search_path = '' as $$
declare
  v_url text := (select value from private.settings where key = 'jobs_url');
  v_secret text := (select value from private.settings where key = 'jobs_secret');
begin
  if v_url is null or v_secret is null then return; end if;
  if not exists (select 1 from pgmq.q_media_jobs where vt <= now())
     and not exists (select 1 from pgmq.q_tryon_jobs where vt <= now())
     and not exists (select 1 from pgmq.q_model3d_jobs where vt <= now()) then
    return;
  end if;
  perform net.http_post(
    url := v_url,
    headers := jsonb_build_object('content-type', 'application/json', 'x-job-secret', v_secret),
    body := '{}'::jsonb,
    timeout_milliseconds := 55000
  );
end;
$$;

alter publication supabase_realtime add table public.avatar_models;
